export const STT_LANGUAGES = [
  { code: "en-US", label: "English (US)" },
  { code: "en-GB", label: "English (UK)" },
  { code: "ja-JP", label: "Japanese" },
  { code: "zh-CN", label: "Chinese (Simplified)" },
  { code: "zh-TW", label: "Chinese (Traditional)" },
  { code: "ko-KR", label: "Korean" },
  { code: "es-ES", label: "Spanish" },
  { code: "fr-FR", label: "French" },
  { code: "de-DE", label: "German" },
  { code: "pt-BR", label: "Portuguese (Brazil)" },
  { code: "it-IT", label: "Italian" },
  { code: "hi-IN", label: "Hindi" },
  { code: "ar-SA", label: "Arabic" },
  { code: "ru-RU", label: "Russian" },
  { code: "th-TH", label: "Thai" },
  { code: "vi-VN", label: "Vietnamese" },
] as const;

/** BCP-47 codes supported by gemini-3.5-live-translate-preview */
export const TRANSLATION_LANGUAGES = [
  { id: "af", label: "Afrikaans" },
  { id: "ak", label: "Akan" },
  { id: "sq", label: "Albanian" },
  { id: "am", label: "Amharic" },
  { id: "ar", label: "Arabic" },
  { id: "hy", label: "Armenian" },
  { id: "az", label: "Azerbaijani" },
  { id: "eu", label: "Basque" },
  { id: "be", label: "Belarusian" },
  { id: "bn", label: "Bengali" },
  { id: "bg", label: "Bulgarian" },
  { id: "my", label: "Burmese (Myanmar)" },
  { id: "ca", label: "Catalan" },
  { id: "zh-Hans", label: "Chinese (Simplified)" },
  { id: "zh-Hant", label: "Chinese (Traditional)" },
  { id: "hr", label: "Croatian" },
  { id: "cs", label: "Czech" },
  { id: "da", label: "Danish" },
  { id: "nl", label: "Dutch" },
  { id: "en", label: "English" },
  { id: "et", label: "Estonian" },
  { id: "fil", label: "Filipino" },
  { id: "fi", label: "Finnish" },
  { id: "fr", label: "French" },
  { id: "gl", label: "Galician" },
  { id: "ka", label: "Georgian" },
  { id: "de", label: "German" },
  { id: "el", label: "Greek" },
  { id: "gu", label: "Gujarati" },
  { id: "ha", label: "Hausa" },
  { id: "he", label: "Hebrew" },
  { id: "hi", label: "Hindi" },
  { id: "hu", label: "Hungarian" },
  { id: "is", label: "Icelandic" },
  { id: "id", label: "Indonesian" },
  { id: "it", label: "Italian" },
  { id: "ja", label: "Japanese" },
  { id: "jv", label: "Javanese" },
  { id: "kn", label: "Kannada" },
  { id: "kk", label: "Kazakh" },
  { id: "km", label: "Khmer" },
  { id: "rw", label: "Kinyarwanda" },
  { id: "ko", label: "Korean" },
  { id: "lo", label: "Lao" },
  { id: "lv", label: "Latvian" },
  { id: "lt", label: "Lithuanian" },
  { id: "mk", label: "Macedonian" },
  { id: "ms", label: "Malay" },
  { id: "ml", label: "Malayalam" },
  { id: "mr", label: "Marathi" },
  { id: "mn", label: "Mongolian" },
  { id: "ne", label: "Nepali" },
  { id: "no", label: "Norwegian" },
  { id: "fa", label: "Persian" },
  { id: "pl", label: "Polish" },
  { id: "pt-BR", label: "Portuguese (Brazil)" },
  { id: "pt-PT", label: "Portuguese (Portugal)" },
  { id: "pa", label: "Punjabi" },
  { id: "ro", label: "Romanian" },
  { id: "ru", label: "Russian" },
  { id: "sr", label: "Serbian" },
  { id: "sd", label: "Sindhi" },
  { id: "si", label: "Sinhala" },
  { id: "sk", label: "Slovak" },
  { id: "sl", label: "Slovenian" },
  { id: "es", label: "Spanish" },
  { id: "su", label: "Sundanese" },
  { id: "sw", label: "Swahili" },
  { id: "sv", label: "Swedish" },
  { id: "ta", label: "Tamil" },
  { id: "te", label: "Telugu" },
  { id: "th", label: "Thai" },
  { id: "tr", label: "Turkish" },
  { id: "uk", label: "Ukrainian" },
  { id: "ur", label: "Urdu" },
  { id: "uz", label: "Uzbek" },
  { id: "vi", label: "Vietnamese" },
  { id: "zu", label: "Zulu" },
] as const;

export type LiveSessionMode = "conversation" | "translate" | "bidirectional";

const LEGACY_LANGUAGE_IDS: Record<string, string> = {
  auto: "en",
  zh: "zh-Hans",
  pt: "pt-BR",
  tl: "fil",
  ceb: "fil",
};

export function languageLabel(id: string): string {
  return TRANSLATION_LANGUAGES.find((l) => l.id === id)?.label ?? id;
}

export function normalizeLanguageId(id: string): string {
  if (TRANSLATION_LANGUAGES.some((l) => l.id === id)) return id;
  return LEGACY_LANGUAGE_IDS[id] ?? "en";
}