import { ModelConfig } from "./types";

export const MODELS: Record<string, ModelConfig> = {
  "claude-haiku-4-5": {
    id: "claude-haiku-4-5",
    publisher: "anthropic",
    modelId: "claude-haiku-4-5@20251001:streamRawPredict",
    displayName: "Claude 4.5 Haiku",
    maxInputTokens: 200000,
    maxOutputTokens: 8192,
    icon: "zap",
    color: "#10B981",
    description: "Fast and efficient with memory support",
    pricing: { input: 0.001, output: 0.005 },
    supportsMemory: true,
    endpointSupport: ["vertex_ai"],
  },
  "claude-opus-4-8": {
    id: "claude-opus-4-8",
    publisher: "anthropic",
    modelId: "claude-opus-4-8:streamRawPredict",
    displayName: "Claude 4.8 Opus",
    maxInputTokens: 1000000,
    maxOutputTokens: 128000,
    icon: "crown",
    color: "#991B1B",
    description: "Latest flagship model with 1M context, adaptive thinking, and memory",
    pricing: { input: 0.005, output: 0.025 },
    supports1MContext: true,
    supportsMemory: true,
    supportsDeepThinking: true,
    defaultThinkingLevel: "none",
    endpointSupport: ["vertex_ai"],
  },
  "claude-sonnet-4-6": {
    id: "claude-sonnet-4-6",
    publisher: "anthropic",
    modelId: "claude-sonnet-4-6:streamRawPredict",
    displayName: "Claude 4.6 Sonnet",
    maxInputTokens: 1000000,
    maxOutputTokens: 64000,
    icon: "rocket",
    color: "#7C3AED",
    description: "Latest Sonnet with enhanced capabilities (supports 1M context + memory)",
    pricing: { input: 0.003, output: 0.015, inputPremium: 0.006, outputPremium: 0.0225 },
    supports1MContext: true,
    supportsMemory: true,
    endpointSupport: ["vertex_ai"],
  },
  "gemini-3-pro-deep-think": {
    id: "gemini-3-pro-deep-think",
    publisher: "google",
    modelId: "gemini-3.1-pro-preview:generateContent",
    aiStudioModelId: "gemini-3.1-pro-preview",
    displayName: "Gemini 3.1 Pro Deep Think",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "brain",
    color: "#9334E6",
    description: "Gemini 3.1 Pro with extended thinking + Google Search grounding",
    pricing: { input: 0.0025, output: 0.015 },
    supportsGrounding: true,
    supportsDeepThinking: true,
    defaultThinkingLevel: "high",
    endpointSupport: ["ai_studio"],
  },
  "gemini-3-1-pro": {
    id: "gemini-3-1-pro",
    publisher: "google",
    modelId: "gemini-3.1-pro-preview:streamGenerateContent",
    aiStudioModelId: "gemini-3.1-pro-preview",
    displayName: "Gemini 3.1 Pro",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "star",
    color: "#1A73E8",
    description: "Latest Gemini Pro with enhanced reasoning and 1M context",
    pricing: { input: 0.0025, output: 0.015 },
    supportsGrounding: true,
    defaultGrounding: true,
    supportsDeepThinking: true,
    defaultThinkingLevel: "none",
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "gemini-3-1-pro-customtools": {
    id: "gemini-3-1-pro-customtools",
    publisher: "google",
    modelId: "gemini-3.1-pro-preview-customtools:streamGenerateContent",
    aiStudioModelId: "gemini-3.1-pro-preview-customtools",
    displayName: "Gemini 3.1 Pro (Agent Tools)",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "star",
    color: "#1A73E8",
    description: "Optimized for agentic workflows with custom tools and bash",
    pricing: { input: 0.0025, output: 0.015 },
    supportsGrounding: true,
    defaultGrounding: true,
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "gemini-3-1-flash-lite": {
    id: "gemini-3-1-flash-lite",
    publisher: "google",
    modelId: "gemini-3.1-flash-lite:streamGenerateContent",
    aiStudioModelId: "gemini-3.1-flash-lite",
    displayName: "Gemini 3.1 Flash Lite",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "zap",
    color: "#34D399",
    description: "GA low-latency model for high-volume tasks with 1M context",
    pricing: { input: 0.00025, output: 0.0015 },
    supportsGrounding: true,
    defaultGrounding: true,
    supportsDeepThinking: true,
    defaultThinkingLevel: "none",
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "gemini-3-5-flash": {
    id: "gemini-3-5-flash",
    publisher: "google",
    modelId: "gemini-3.5-flash:streamGenerateContent",
    aiStudioModelId: "gemini-3.5-flash",
    displayName: "Gemini 3.5 Flash",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "zap",
    color: "#059669",
    description: "GA agentic & coding model with frontier performance at Flash speed",
    pricing: { input: 0.0015, output: 0.009 },
    supportsGrounding: true,
    defaultGrounding: true,
    supportsDeepThinking: true,
    defaultThinkingLevel: "medium",
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "gemini-3-5-flash-lite": {
    id: "gemini-3-5-flash-lite",
    publisher: "google",
    modelId: "gemini-3.5-flash-lite:streamGenerateContent",
    aiStudioModelId: "gemini-3.5-flash-lite",
    displayName: "Gemini 3.5 Flash-Lite",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "zap",
    color: "#14B8A6",
    description: "Fastest 3.5-class model for high-throughput agentic & document workflows (~350 tok/s)",
    pricing: { input: 0.0003, output: 0.0025 },
    supportsGrounding: true,
    defaultGrounding: true,
    supportsDeepThinking: true,
    defaultThinkingLevel: "minimal",
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "gemini-3-5-flash-cyber": {
    id: "gemini-3-5-flash-cyber",
    publisher: "google",
    modelId: "gemini-3.5-flash-cyber:streamGenerateContent",
    aiStudioModelId: "gemini-3.5-flash-cyber",
    displayName: "Gemini 3.5 Flash Cyber",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "shield",
    color: "#0EA5E9",
    description: "Cybersecurity model for finding, validating & patching vulnerabilities (limited pilot access)",
    pricing: { input: 0.0015, output: 0.009 },
    supportsGrounding: true,
    supportsDeepThinking: true,
    defaultThinkingLevel: "medium",
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "gemini-3-6-flash": {
    id: "gemini-3-6-flash",
    publisher: "google",
    modelId: "gemini-3.6-flash:streamGenerateContent",
    aiStudioModelId: "gemini-3.6-flash",
    displayName: "Gemini 3.6 Flash",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "zap",
    color: "#10B981",
    description: "Latest Flash model for agentic workflows, coding, and multimodal tasks",
    pricing: { input: 0.0015, output: 0.0075 },
    supportsGrounding: true,
    defaultGrounding: true,
    supportsDeepThinking: true,
    defaultThinkingLevel: "medium",
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "nano-banana-pro": {
    id: "nano-banana-pro",
    publisher: "google",
    modelId: "gemini-3-pro-image:generateContent",
    aiStudioModelId: "gemini-3-pro-image",
    displayName: "Nano Banana Pro",
    maxInputTokens: 32768,
    maxOutputTokens: 8192,
    icon: "image",
    color: "#FFD93D",
    description: "GA image generation and editing (Gemini 3 Pro Image)",
    pricing: { input: 0.0025, output: 0.015 },
    supportsImageGeneration: true,
    endpointSupport: ["ai_studio"],
  },
  "nano-banana-2": {
    id: "nano-banana-2",
    publisher: "google",
    modelId: "gemini-3.1-flash-image:generateContent",
    aiStudioModelId: "gemini-3.1-flash-image",
    displayName: "Nano Banana 2",
    maxInputTokens: 32768,
    maxOutputTokens: 8192,
    icon: "image",
    color: "#FFA726",
    description: "GA fast image generation and editing (Gemini 3.1 Flash Image)",
    pricing: { input: 0.0003, output: 0.0012 },
    supportsImageGeneration: true,
    endpointSupport: ["ai_studio"],
  },
  "nano-banana-2-lite": {
    id: "nano-banana-2-lite",
    publisher: "google",
    modelId: "gemini-3.1-flash-lite-image:generateContent",
    aiStudioModelId: "gemini-3.1-flash-lite-image",
    displayName: "Nano Banana 2 Lite",
    maxInputTokens: 32768,
    maxOutputTokens: 8192,
    icon: "image",
    color: "#AED581",
    description: "Lightweight fast image generation and editing (Gemini 3.1 Flash Lite Image)",
    pricing: { input: 0.0001, output: 0.0004 },
    supportsImageGeneration: true,
    endpointSupport: ["ai_studio"],
  },
  "gemini-deep-research": {
    id: "gemini-deep-research",
    publisher: "google",
    modelId: "deep-research-preview-04-2026:streamGenerateContent",
    aiStudioModelId: "deep-research-preview-04-2026",
    displayName: "Gemini Deep Research",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "search",
    color: "#EA4335",
    description: "Multi-step web research (Standard or Max) with planning, visuals, and tools",
    pricing: { input: 0.0025, output: 0.01 },
    supportsGrounding: true,
    supportsDeepResearch: true,
    endpointSupport: ["ai_studio"],
  },
  "grok-4-1": {
    id: "grok-4-1",
    publisher: "xai",
    modelId: "grok-4-1",
    displayName: "Grok 4.1",
    maxInputTokens: 131072,
    maxOutputTokens: 16384,
    icon: "crown",
    color: "#E91E63",
    description: "xAI's latest flagship model with advanced reasoning",
    pricing: { input: 0.005, output: 0.025 },
    supportsDeepThinking: true,
    endpointSupport: ["xai"],
  },
  "grok-3": {
    id: "grok-3",
    publisher: "xai",
    modelId: "grok-3",
    displayName: "Grok 3",
    maxInputTokens: 131072,
    maxOutputTokens: 8192,
    icon: "rocket",
    color: "#1DA1F2",
    description: "xAI's most capable model with real-time knowledge",
    pricing: { input: 0.003, output: 0.015 },
    endpointSupport: ["xai"],
  },
  "grok-3-fast": {
    id: "grok-3-fast",
    publisher: "xai",
    modelId: "grok-3-fast",
    displayName: "Grok 3 Fast",
    maxInputTokens: 131072,
    maxOutputTokens: 8192,
    icon: "zap",
    color: "#17BF63",
    description: "Fast, efficient reasoning with real-time X data access",
    pricing: { input: 0.0005, output: 0.0025 },
    endpointSupport: ["xai"],
  },
  "grok-3-mini": {
    id: "grok-3-mini",
    publisher: "xai",
    modelId: "grok-3-mini",
    displayName: "Grok 3 Mini",
    maxInputTokens: 131072,
    maxOutputTokens: 8192,
    icon: "zap",
    color: "#794BC4",
    description: "Lightweight reasoning model with thinking capabilities",
    pricing: { input: 0.0003, output: 0.0005 },
    supportsDeepThinking: true,
    endpointSupport: ["xai"],
  },
  "openrouter-auto": {
    id: "openrouter-auto",
    publisher: "openrouter",
    modelId: "openrouter/auto",
    displayName: "OpenRouter Auto",
    maxInputTokens: 200000,
    maxOutputTokens: 16384,
    icon: "target",
    color: "#6366F1",
    description: "Auto-selects best model for your prompt",
    pricing: { input: 0.002, output: 0.008 },
    endpointSupport: ["openrouter"],
  },
  "openrouter-claude-opus-4-8": {
    id: "openrouter-claude-opus-4-8",
    publisher: "openrouter",
    modelId: "anthropic/claude-opus-4.8",
    displayName: "Claude 4.8 Opus (OR)",
    maxInputTokens: 1000000,
    maxOutputTokens: 128000,
    icon: "crown",
    color: "#991B1B",
    description: "Claude 4.8 Opus via OpenRouter",
    pricing: { input: 0.005, output: 0.025 },
    supports1MContext: true,
    endpointSupport: ["openrouter"],
  },
  "openrouter-claude-sonnet-4-6": {
    id: "openrouter-claude-sonnet-4-6",
    publisher: "openrouter",
    modelId: "anthropic/claude-sonnet-4-6",
    displayName: "Claude 4.6 Sonnet (OR)",
    maxInputTokens: 1000000,
    maxOutputTokens: 64000,
    icon: "rocket",
    color: "#7C3AED",
    description: "Claude 4.6 Sonnet via OpenRouter",
    pricing: { input: 0.003, output: 0.015 },
    supports1MContext: true,
    endpointSupport: ["openrouter"],
  },
  "openrouter-gpt-4o": {
    id: "openrouter-gpt-4o",
    publisher: "openrouter",
    modelId: "openai/gpt-4o",
    displayName: "GPT-4o (OR)",
    maxInputTokens: 128000,
    maxOutputTokens: 16384,
    icon: "brain",
    color: "#10A37F",
    description: "OpenAI GPT-4o via OpenRouter",
    pricing: { input: 0.0025, output: 0.01 },
    endpointSupport: ["openrouter"],
  },
  "openrouter-llama-405b": {
    id: "openrouter-llama-405b",
    publisher: "openrouter",
    modelId: "meta-llama/llama-3.3-405b-instruct",
    displayName: "Llama 3.3 405B (OR)",
    maxInputTokens: 131072,
    maxOutputTokens: 16384,
    icon: "crown",
    color: "#0467DF",
    description: "Meta's largest open model via OpenRouter",
    pricing: { input: 0.002, output: 0.006 },
    endpointSupport: ["openrouter"],
  },
  "openrouter-deepseek-r1": {
    id: "openrouter-deepseek-r1",
    publisher: "openrouter",
    modelId: "deepseek/deepseek-r1",
    displayName: "DeepSeek R1 (OR)",
    maxInputTokens: 65536,
    maxOutputTokens: 8192,
    icon: "brain",
    color: "#FF6B35",
    description: "DeepSeek reasoning model via OpenRouter",
    pricing: { input: 0.0014, output: 0.0056 },
    supportsDeepThinking: true,
    endpointSupport: ["openrouter"],
  },
  "openrouter-gemini-3-pro": {
    id: "openrouter-gemini-3-pro",
    publisher: "openrouter",
    modelId: "google/gemini-3-pro",
    displayName: "Gemini 3 Pro (OR)",
    maxInputTokens: 2097152,
    maxOutputTokens: 65536,
    icon: "star",
    color: "#4285F4",
    description: "Google's next-gen multimodal via OpenRouter",
    pricing: { input: 0.0025, output: 0.015 },
    endpointSupport: ["openrouter"],
  },
  "openrouter-gemini-3-1-pro": {
    id: "openrouter-gemini-3-1-pro",
    publisher: "openrouter",
    modelId: "google/gemini-3.1-pro-preview",
    displayName: "Gemini 3.1 Pro (OR)",
    maxInputTokens: 2097152,
    maxOutputTokens: 65536,
    icon: "star",
    color: "#1A73E8",
    description: "Google's latest Gemini Pro via OpenRouter",
    pricing: { input: 0.0025, output: 0.015 },
    endpointSupport: ["openrouter"],
  },
  "openrouter-gemini-3-5-flash": {
    id: "openrouter-gemini-3-5-flash",
    publisher: "openrouter",
    modelId: "google/gemini-3.5-flash",
    displayName: "Gemini 3.5 Flash (OR)",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "zap",
    color: "#059669",
    description: "Agentic & coding model via OpenRouter",
    pricing: { input: 0.0015, output: 0.009 },
    supportsDeepThinking: true,
    endpointSupport: ["openrouter"],
  },
  "openrouter-gemini-3-5-flash-lite": {
    id: "openrouter-gemini-3-5-flash-lite",
    publisher: "openrouter",
    modelId: "google/gemini-3.5-flash-lite",
    displayName: "Gemini 3.5 Flash-Lite (OR)",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "zap",
    color: "#14B8A6",
    description: "Fastest 3.5-class high-throughput model via OpenRouter",
    pricing: { input: 0.0003, output: 0.0025 },
    supportsDeepThinking: true,
    endpointSupport: ["openrouter"],
  },
  "openrouter-gemini-3-5-flash-cyber": {
    id: "openrouter-gemini-3-5-flash-cyber",
    publisher: "openrouter",
    modelId: "google/gemini-3.5-flash-cyber",
    displayName: "Gemini 3.5 Flash Cyber (OR)",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "shield",
    color: "#0EA5E9",
    description: "Cybersecurity vulnerability model via OpenRouter (limited access)",
    pricing: { input: 0.0015, output: 0.009 },
    supportsDeepThinking: true,
    endpointSupport: ["openrouter"],
  },
  "openrouter-gemini-3-1-flash-lite": {
    id: "openrouter-gemini-3-1-flash-lite",
    publisher: "openrouter",
    modelId: "google/gemini-3.1-flash-lite",
    displayName: "Gemini 3.1 Flash Lite (OR)",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "zap",
    color: "#34D399",
    description: "Low-latency budget model via OpenRouter",
    pricing: { input: 0.00025, output: 0.0015 },
    supportsDeepThinking: true,
    endpointSupport: ["openrouter"],
  },
  "openrouter-gemini-3-deep-think": {
    id: "openrouter-gemini-3-deep-think",
    publisher: "openrouter",
    modelId: "google/gemini-3-pro-thinking",
    displayName: "Gemini 3 Deep Think (OR)",
    maxInputTokens: 2097152,
    maxOutputTokens: 65536,
    icon: "brain",
    color: "#9334E6",
    description: "Deep Thinking + reasoning via OpenRouter",
    pricing: { input: 0.0025, output: 0.015 },
    supportsDeepThinking: true,
    endpointSupport: ["openrouter"],
  },
  "openrouter-gemini-3-6-flash": {
    id: "openrouter-gemini-3-6-flash",
    publisher: "openrouter",
    modelId: "google/gemini-3.6-flash",
    displayName: "Gemini 3.6 Flash (OR)",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "zap",
    color: "#10B981",
    description: "Latest Flash model for agentic workflows via OpenRouter",
    pricing: { input: 0.0015, output: 0.0075 },
    supportsDeepThinking: true,
    endpointSupport: ["openrouter"],
  },
  "kilocode-claude-opus-4-8": {
    id: "kilocode-claude-opus-4-8",
    publisher: "kilocode",
    modelId: "anthropic/claude-opus-4.8",
    displayName: "Claude 4.8 Opus (Kilo)",
    maxInputTokens: 1000000,
    maxOutputTokens: 128000,
    icon: "crown",
    color: "#991B1B",
    description: "Claude 4.8 Opus via Kilo Code",
    pricing: { input: 0.005, output: 0.025 },
    supports1MContext: true,
    endpointSupport: ["kilocode"],
  },
  "kilocode-claude-sonnet-4-6": {
    id: "kilocode-claude-sonnet-4-6",
    publisher: "kilocode",
    modelId: "anthropic/claude-sonnet-4-6",
    displayName: "Claude 4.6 Sonnet (Kilo)",
    maxInputTokens: 1000000,
    maxOutputTokens: 64000,
    icon: "rocket",
    color: "#7C3AED",
    description: "Claude 4.6 Sonnet via Kilo Code",
    pricing: { input: 0.003, output: 0.015 },
    supports1MContext: true,
    endpointSupport: ["kilocode"],
  },
  "kilocode-deepseek": {
    id: "kilocode-deepseek",
    publisher: "kilocode",
    modelId: "deepseek/deepseek-chat",
    displayName: "DeepSeek V3 (Kilo)",
    maxInputTokens: 65536,
    maxOutputTokens: 8192,
    icon: "zap",
    color: "#8BC34A",
    description: "DeepSeek V3 via Kilo Code - fast and efficient",
    pricing: { input: 0.00027, output: 0.0011 },
    endpointSupport: ["kilocode"],
  },
  "kilocode-gemini-3-pro": {
    id: "kilocode-gemini-3-pro",
    publisher: "kilocode",
    modelId: "google/gemini-3-pro",
    displayName: "Gemini 3 Pro (Kilo)",
    maxInputTokens: 2097152,
    maxOutputTokens: 65536,
    icon: "star",
    color: "#4285F4",
    description: "Gemini 3 Pro optimized for coding via Kilo Code",
    pricing: { input: 0.0025, output: 0.015 },
    endpointSupport: ["kilocode"],
  },
  "kilocode-gemini-3-1-pro": {
    id: "kilocode-gemini-3-1-pro",
    publisher: "kilocode",
    modelId: "google/gemini-3.1-pro-preview",
    displayName: "Gemini 3.1 Pro (Kilo)",
    maxInputTokens: 2097152,
    maxOutputTokens: 65536,
    icon: "star",
    color: "#1A73E8",
    description: "Gemini 3.1 Pro optimized for coding via Kilo Code",
    pricing: { input: 0.0025, output: 0.015 },
    endpointSupport: ["kilocode"],
  },
  "kilocode-gemini-3-5-flash": {
    id: "kilocode-gemini-3-5-flash",
    publisher: "kilocode",
    modelId: "google/gemini-3.5-flash",
    displayName: "Gemini 3.5 Flash (Kilo)",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "zap",
    color: "#059669",
    description: "Gemini 3.5 Flash optimized for coding via Kilo Code",
    pricing: { input: 0.0015, output: 0.009 },
    supportsDeepThinking: true,
    endpointSupport: ["kilocode"],
  },
  "kilocode-gemini-3-5-flash-lite": {
    id: "kilocode-gemini-3-5-flash-lite",
    publisher: "kilocode",
    modelId: "google/gemini-3.5-flash-lite",
    displayName: "Gemini 3.5 Flash-Lite (Kilo)",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "zap",
    color: "#14B8A6",
    description: "Gemini 3.5 Flash-Lite via Kilo Code",
    pricing: { input: 0.0003, output: 0.0025 },
    supportsDeepThinking: true,
    endpointSupport: ["kilocode"],
  },
  "kilocode-gemini-3-5-flash-cyber": {
    id: "kilocode-gemini-3-5-flash-cyber",
    publisher: "kilocode",
    modelId: "google/gemini-3.5-flash-cyber",
    displayName: "Gemini 3.5 Flash Cyber (Kilo)",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "shield",
    color: "#0EA5E9",
    description: "Gemini 3.5 Flash Cyber via Kilo Code (limited access)",
    pricing: { input: 0.0015, output: 0.009 },
    supportsDeepThinking: true,
    endpointSupport: ["kilocode"],
  },
  "kilocode-gemini-3-1-flash-lite": {
    id: "kilocode-gemini-3-1-flash-lite",
    publisher: "kilocode",
    modelId: "google/gemini-3.1-flash-lite",
    displayName: "Gemini 3.1 Flash Lite (Kilo)",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "zap",
    color: "#34D399",
    description: "Gemini 3.1 Flash Lite via Kilo Code",
    pricing: { input: 0.00025, output: 0.0015 },
    supportsDeepThinking: true,
    endpointSupport: ["kilocode"],
  },
  "kilocode-gemini-3-deep-think": {
    id: "kilocode-gemini-3-deep-think",
    publisher: "kilocode",
    modelId: "google/gemini-3-pro-thinking",
    displayName: "Gemini 3 Deep Think (Kilo)",
    maxInputTokens: 2097152,
    maxOutputTokens: 65536,
    icon: "brain",
    color: "#9334E6",
    description: "Deep Thinking + reasoning via Kilo Code",
    pricing: { input: 0.0025, output: 0.015 },
    supportsDeepThinking: true,
    endpointSupport: ["kilocode"],
  },
  "kilocode-gemini-3-6-flash": {
    id: "kilocode-gemini-3-6-flash",
    publisher: "kilocode",
    modelId: "google/gemini-3.6-flash",
    displayName: "Gemini 3.6 Flash (Kilo)",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "zap",
    color: "#10B981",
    description: "Gemini 3.6 Flash optimized for coding via Kilo Code",
    pricing: { input: 0.0015, output: 0.0075 },
    supportsDeepThinking: true,
    endpointSupport: ["kilocode"],
  },
};

export const ENDPOINT_URLS = {
  vertex_ai: "https://aiplatform.googleapis.com",
  ai_studio: "https://generativelanguage.googleapis.com",
  openrouter: "https://openrouter.ai/api/v1",
  xai: "https://api.x.ai/v1",
  kilocode: "https://api.kilocode.ai/v1",
};
